version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    command:
      - ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/

volumes:
  db_data: